version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773
      - 52773:52773
      - 53773
      - 4040:8080
      - 4041:8081
    volumes:
      - ./:/irisdev/app